version: '3'
services:
  ui:
#    environment:
#      - ADMIN_EMAIL=${ADMIN_EMAIL}
#      - DB_HOSTNAME=django_db
#      - DB_DATABASE=${DB_DATABASE}
#      - DB_USER=${DB_USER}
#      - DB_PASSWORD=${DB_PASSWORD}
#      - DB_PORT=${DB_PORT}
#      - PORT=${PORT}
    # command: bash 
    #python3 manage.py runserver 0.0.0.0:${PORT}
    build:
      dockerfile: docker/ui/Dockerfile.dev
      context: ..
      args:
        WORKDIR: ${WORKDIR}
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        DJANGO_DB_HOSTNAME: django_db
        DJANGO_DB_DATABASE: ${DJANGO_DB_DATABASE}
        DJANGO_DB_USER: ${DJANGO_DB_USER}
        DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD}
        ODC_DB_HOSTNAME: ${ODC_DB_HOSTNAME}
        ODC_DB_DATABASE: ${ODC_DB_DATABASE}
        ODC_DB_USER: ${ODC_DB_USER}
        ODC_DB_PASSWORD: ${ODC_DB_PASSWORD}
        REDIS_HOST: redis
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    ports:
      - ${HOST_PORT}:80
    volumes:
      # - ../:${WORKDIR}
      # - ${WORKDIR}/config
      # - ${WORKDIR}/docker
      - ../apps:${WORKDIR}/apps
      - ../data_cube_ui:${WORKDIR}/data_cube_ui
      - ../datacube_env:${WORKDIR}/datacube_env
      - ../db_backups:${WORKDIR}/db_backups
      - ../log:${WORKDIR}/log
      - ../scripts:${WORKDIR}/scripts
      - ../static:${WORKDIR}/static
      - ../templates:${WORKDIR}/templates
      - ../utils:${WORKDIR}/utils
      # - ../apps:${WORKDIR}/apps
      # - ../config:${WORKDIR}/config
      # - ../data_cube_ui:${WORKDIR}/data_cube_ui
      # - ../db_backups:${WORKDIR}/db_backups
      # - ../scripts:${WORKDIR}/scripts
      # - ../static:${WORKDIR}/static
      # - ../templates:${WORKDIR}/templates
      # - ../utils:${WORKDIR}/utils
    networks:
      - odc
    depends_on:
      - django_db
      - redis
  django_db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=${DJANGO_DB_DATABASE}
      - POSTGRES_USER=${DJANGO_DB_USER}
      - POSTGRES_PASSWORD=${DJANGO_DB_PASSWORD}
    volumes:
      - django-db-vol:/var/lib/postgresql/data
    networks:
      - odc
  redis:
    image: redis:5.0.9
    networks:
      - odc
volumes:
  django-db-vol:
    external: true
networks:
  odc:
    external: true