version: '3'
services:
  ui:
#    environment:
#      - ADMIN_EMAIL=${ADMIN_EMAIL}
#      - DB_HOSTNAME=django_db
#      - DB_DATABASE=${DB_DATABASE}
#      - DB_USER=${DB_USER}
#      - DB_PASSWORD=${DB_PASSWORD}
#      - DB_PORT=${DB_PORT}
#      - PORT=${PORT}
    # command: bash 
    #python3 manage.py runserver 0.0.0.0:${PORT}
    build:
      dockerfile: docker/ui/Dockerfile.dev
      context: ..
      args:
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        DJANGO_DB_HOSTNAME: django_db
        DJANGO_DB_DATABASE: ${DJANGO_DB_DATABASE}
        DJANGO_DB_USER: ${DJANGO_DB_USER}
        DJANGO_DB_PASSWORD: ${DJANGO_DB_PASSWORD}
        ODC_DB_HOSTNAME: ${ODC_DB_HOSTNAME}
        ODC_DB_DATABASE: ${ODC_DB_DATABASE}
        ODC_DB_USER: ${ODC_DB_USER}
        ODC_DB_PASSWORD: ${ODC_DB_PASSWORD}
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ../:/app
    networks:
      - odc
    depends_on:
      [django_db]
  django_db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=${DJANGO_DB_DATABASE}
      - POSTGRES_USER=${DJANGO_DB_USER}
      - POSTGRES_PASSWORD=${DJANGO_DB_PASSWORD}
    networks:
      - odc
networks:
  odc:
    external: true