version: '3'
services:
  ui:
#    environment:
#      - ADMIN_EMAIL=${ADMIN_EMAIL}
#      - DB_HOSTNAME=django_db
#      - DB_DATABASE=${DB_DATABASE}
#      - DB_USER=${DB_USER}
#      - DB_PASSWORD=${DB_PASSWORD}
#      - DB_PORT=${DB_PORT}
#      - PORT=${PORT}
    # command: bash 
    #python3 manage.py runserver 0.0.0.0:${PORT}
    build:
      dockerfile: docker/ui/Dockerfile.dev
      context: ..
      args:
        ADMIN_EMAIL: ${ADMIN_EMAIL}
        DB_HOSTNAME: django_db
        DB_DATABASE: ${DB_DATABASE}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_PORT: ${DB_PORT}
        PORT: ${PORT}
    ports:
      - "${PORT}:80"
    # volumes:
      # - ..:/app
    networks:
      - odc
    depends_on:
      [django_db]
  django_db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - odc
networks:
  odc:
    external: true